- title: My home
  link: /

  children:
  - title: My profile
    link: /profile

  - title: My portfolio
    link: /portfolio

  - title: My workshop
    link: /work-in-progress

  - title: My favorites
    link: /work-in-progress

  - title: My messages
    link: /messages

  - title: My preferences
    link: /profile-preferences

- title: Challenges
  link: /challenges

  children:
  - title: Cast votes
    link: /challenges-votes

  - title: View results
    link: /challenges-resultes

  - title: Submit photos
    link: /challenges-submissiones-photo

  - title: Challenge Archives
    link: /work-in-progress

  - title: Challenge History
    link: /work-in-progress
    
  - title: Challenges Rules
    link: /work-in-progress

- title: Community
  link: /work-in-progress

  children:
  - title: Forums
    link: /forums
  
  - title: Critique Club
    link: /work-in-progress
  
  - title: Poll Archives
    link: /work-in-progress
  
  - title: Site Favorites
    link: /work-in-progress
  
  - title: Community Projects
    link: /work-in-progress
  
  - title: Photographer Profiles
    link: /work-in-progress
  
  - title: Photographer Interviews
    link: /work-in-progress
  
  - title: Top 10 Statistics
    link: /work-in-progress
  
  - title: Who's online
    link: /work-in-progress

- title: League
  link: /work-in-progress

  children:
  - title: Overview
    link: /work-in-progress
  
  - title: DPL FAQ
    link: /work-in-progress
  
  - title: DPL Rules
    link: /work-in-progress
  
  - title: About the DPL
    link: /work-in-progress

- title: Photos
  link: /work-in-progress

  children:
  - title: Browse
    link: /work-in-progress
  
  - title: Galleries
    link: /work-in-progress
  
  - title: Site Favorites
    link: /work-in-progress
  
  - title: Search
    link: /work-in-progress

- title: Equipment
  link: /work-in-progress

  children:
  - title: Cameras
    link: /cameras
  
  - title: Lenses
    link: /lenses
  
  - title: Shop Equipment
    link: /work-in-progress

- title: Learn
  link: /work-in-progress

  children:
  - title: How'd They Do That
    link: /work-in-progress
  
  - title: Tutorials
    link: /work-in-progress

- title: DPCPrints
  link: /work-in-progress

  children:
  - title: Browse
    link: /work-in-progress
  
  - title: Search
    link: /work-in-progress
  
  - title: Help
    link: /work-in-progress

- title: Help
  link: /work-in-progress

  children:
  - title: Contact Us
    link: /work-in-progress
  
  - title: FAQ
    link: /work-in-progress
  
  - title: Glossary
    link: /work-in-progress
  
  - title: About
    link: /work-in-progress
  
  - title: Site Rules
    link: /work-in-progress
